linux-system-roles/vpn

tasks/main.yml
templates/libreswan-host-to-host.secrets.j2
tests/tasks/cleanup.yml
tests/tests_host_to_host_cert.yml

do not use `namespace`
The run_once behavior is different when using python2/ansible28/jinja27
we are not guaranteed that the run_once host is the first host in
hostvars - so instead, find the hostvars value that has __vpn_psks
The mainhost is not guaranteed to be the last one - so save the
cert name assigned to it for use later to verify.

support jinja 2.7

---

README.md
templates/libreswan-host-to-host.conf.j2
templates/libreswan-host-to-host.secrets.j2

Resolves #14.
Changes `leftid`/`rightid` values to reflect the following values in order of preference (1) resolvable user-specified `hostname` (2) `ansible_host` (3) `host` key value. The connection name also synchronizes with the values in `leftid`/`rightid`.

Update conn naming scheme and leftid/rightid values

---

tasks/enable_restart_vpn.yml

The check using `wait_for` to check the ssh port does not work
reliably with qemu based testing, because the IP address inside
the VM is not always resolvable externally, and the port number
is different from `22` as well.  Instead, use the `wait_for_connection`
module which explicitly tests that Ansible can connection to the
host using its transport mechanism, which I think is what this
check is trying to do.

use wait_for_connection instead of wait_for with ssh

---

.github/workflows/tox.yml
.sanity-ansible-ignore-2.10.txt
.sanity-ansible-ignore-2.11.txt
.sanity-ansible-ignore-2.12.txt
.sanity-ansible-ignore-2.9.txt
README.md
ansible_pytest_extra_requirements.txt
filter_plugins/vpn_ipaddr.py
meta/requirements.yml
pytest_extra_requirements.txt
tasks/main.yml
tasks/mesh_conf.yml
templates/libreswan-host-to-host.conf.j2
templates/libreswan-host-to-host.secrets.j2
tests/roles/linux-system-roles.vpn/filter_plugins
tests/unit/test_vpn_ipaddr.py
tox.ini

Use a custom vpn_ipaddr filter which uses the `ipaddress` module.  This is built-in to python3.  Users will need to install `ipaddress` on python 2 controllers.  All versions of EL7 include the `python-ipaddress` package.
This is based on the ansible.netcommon.ipaddr filter, but with most
of the functionality removed except that which is necessary for
the VPN role.

use custom vpn_ipaddr filter

---

tasks/mesh_conf.yml
templates/libreswan-host-to-host.conf.j2
templates/libreswan-host-to-host.secrets.j2
templates/libreswan-mesh.conf.j2
templates/policy.j2
tests/tests_host_to_host_cert.yml
tests/tests_host_to_host_psk.yml
tests/tests_host_to_unmanaged_host.yml

bz#2044640
Commented files by tests_mesh_cert.yml:
```
==> /etc/ipsec.d/mesh.conf <==
#
#
conn private
type=tunnel
left=%defaultroute
==> /etc/ipsec.d/policies/clear <==
#
#
198.51.100.0/24
==> /etc/ipsec.d/policies/private <==
#
#
203.0.113.0/24
==> /etc/ipsec.d/policies/private-or-clear <==
#
#
10.0.2.0/24
169.254.0.0/16
```

System Roles should consistently use ansible_managed in configuration files it manages

---

tasks/set_vars.yml
tests/setup-snapshot.yml
tests/tests_default.yml
vars/main.yml

Some users use `gather_facts: false` in their playbooks.  This changes
the role to work in that case, by gathering only the facts it requires
to run.
CI testing can be sped up by creating a snapshot image pre-installed
with packages.  tests/setup-snapshot.yml can be used by a CI system
to do this.

support gather_facts: false; support setup-snapshot.yml

---

CHANGELOG.md

[1.3.5] - 2022-07-19
--------------------
- none
- none
- gather network facts default_ipv4 default_ipv6 (#56)
Gather fact subset `network` instead of `min`
Ensure facts `default_ipv4` and `default_ipv6`
Ensure all tests work when using ANSIBLE_GATHERING=explicit
- make min_ansible_version a string in meta/main.yml (#57)
The Ansible developers say that `min_ansible_version` in meta/main.yml
must be a `string` value like `"2.9"`, not a `float` value like `2.9`.
- Add CHANGELOG.md (#58)

Version 1.3.5 - CHANGELOG.md [citest skip]

---

tasks/main.yml

Check for existence of openssl without using sudo on the controller
Basically, any task, even package_facts:, will use sudo if using
become=true - so just use "exists" test to check for /usr/bin/openssl

Check for /usr/bin/openssl on controller - do not use package_facts

---

README.md
defaults/main.yml
meta/collection-requirements.yml
tasks/firewall.yml
tasks/main.yml
tasks/selinux.yml
tests/tasks/check_firewall_selinux.yml
tests/tests_defaults_vars.yml
tests/tests_host_to_host_cert.yml
tests/tests_host_to_host_psk.yml
tests/tests_host_to_host_psk_custom.yml
tests/tests_host_to_unmanaged_host.yml
tests/tests_mesh_cert.yml
tests/tests_subnet_to_subnet.yml

- Introduce vpn_manage_firewall to use the firewall role to manage the ipsec service. vpn_manage_firewall is set to true, by default. If the variable is set to false, the firewall configuration is disabled.
- Introduce vpn_manage_selinux to use the selinux role to manage the ports defined in the firewall ipsec service. vpn_manage_selinux is set to true, by default.  If the variable is set to false, the selinux configuration is disabled.
- Add the test check task check_firewall_selinux.yml for verify the ports status.
- Add meta/collection-requirements.yml

Use the firewall role and the selinux role from the vpn role

---

CHANGELOG.md

[1.5.0] - 2022-11-01
--------------------
- Use the firewall role and the selinux role from the vpn role (#70)
- Introduce vpn_manage_firewall to enable the firewall role to manage
the ipsec service. vpn_manage_firewall is set to false, by default.
If the variable is set to false, the firewall configuration is
disabled.
- Introduce vpn_manage_selinux to enable the selinux role to manage
the ports defined in the firewall ipsec service. vpn_manage_selinux
is set to false, by default. If the variable is set to false, the
selinux configuration is disabled.
- Add the test check task check_firewall_selinux.yml for verify the
ports status.
- Add meta/collection-requirements.yml
- none
- none

Version 1.5.0 - CHANGELOG.md [citest skip]

---

README.md

long heading causes problems with md to adoc conversion
The long heading causes problems with md to adoc conversion.  Shorten
the length by using abbreviations.

fix markdown to adoc conversion

---

CHANGELOG.md

[1.5.1] - 2022-11-14
--------------------
- none
- none
- fix markdown to adoc conversion (#73)
long heading causes problems with md to adoc conversion
The long heading causes problems with md to adoc conversion.  Shorten
the length by using abbreviations.

Version 1.5.1 - CHANGELOG.md [citest skip]

---

tests/tasks/check_firewall_selinux.yml

Some systems use `firewalld` by default.  We should only expect the
`ipsec` service is present if the test tells the vpn role to manage
firewall or selinux.

only check for firewall ipsec service if managing firewall

---

CHANGELOG.md

[1.5.2] - 2022-11-21
--------------------
- none
- only check for firewall ipsec service if managing firewall (#76)
Some systems use `firewalld` by default.  We should only expect the
`ipsec` service is present if the test tells the vpn role to manage
firewall or selinux.
- none

Version 1.5.2 - CHANGELOG.md [citest skip]

---

.github/workflows/woke.yml
CHANGELOG.md
tests/tasks/add_hosts.yml
tests/tasks/setup_test.yml
tests/tests_mesh_cert.yml
tests/vars/main.yml

Add a check for usage of terms and language that is considered
non-inclusive. We are using the woke tool for this with a wordlist
that can be found at
https://github.com/linux-system-roles/tox-lsr/blob/main/src/tox_lsr/config_files/woke.yml
Clean up non-inclusive words.
- CHANGELOG.md
- tests/tasks/add_hosts.yml
- tests/tasks/setup_test.yml
- tests/tests_mesh_cert.yml
- tests/vars/main.yml

Add check for non-inclusive language

---

filter_plugins/vpn_ipaddr.py

filter_plugins/vpn_ipaddr.py
- 'except' clause does nothing but pass and there is no explanatory comment.
- Mixing implicit and explicit returns may indicate an error as implicit returns always return None.
Signed-off-by: Noriko Hosoi <nhosoi@redhat.com>

Fix issues found by CodeQL

---

templates/libreswan-host-to-host.conf.j2
templates/libreswan-host-to-host.secrets.j2
templates/libreswan-mesh.conf.j2
templates/policy.j2

Add role name to the generated config files.
```
```
Note: This information is provided to help customers identify that it was generated by System Roles. It may also be used for future analysis.

Fingerprint RHEL System Role managed config files

---

handlers/main.yml

ansible-lint now requires the use of changed_when even for
conditional tasks

ansible-lint - use changed_when for conditional tasks

---

tests/tasks/check_header.yml
tests/templates/get_ansible_managed.j2
tests/tests_host_to_host_cert.yml
tests/tests_mesh_cert.yml

Add the following files: tests/tasks/check_header.yml and
tests/templates/get_ansible_managed.j2.
Use check_header.yml to check generated files for the ansible_managed
and fingerprint headers.
check_header.yml takes these parameters.  `fingerprint` is required,
and one of `__file` or `__file_content`:
* `__file` - the full path of the file to check e.g. `/etc/realmd.conf`
* `__file_content` - the output of `slurp` of the file
* `__fingerprint` - required - the fingerprint string `system_role:$ROLENAME` e.g.
`__fingerprint: "system_role:postfix"`
* `__comment_type` - optional, default `plain` - the type of comments used
e.g. `__comment_type: c` for C/C++-style comments.  `plain` uses `#`.
See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#adding-comments-to-fi …

test: check generated files for ansible_managed, fingerprint

---

tests/tasks/setup_test.yml

Error: This special variable is read-only. (inventory_hostname) (set_fact: inventory_hostname)
var-naming[read-only]: This special variable is read-only. (inventory_hostname) (set_fact: inventory_hostname)

ci: ansible-lint - skip var-naming[read-only]

---

tests/tests_default.yml
tests/tests_defaults_vars.yml
tests/tests_host_to_host_cert.yml
tests/tests_host_to_host_psk.yml
tests/tests_host_to_host_psk_custom.yml
tests/tests_host_to_unmanaged_host.yml
tests/tests_mesh_cert.yml
tests/tests_subnet_to_subnet.yml

tests now run in an environment where the managed node is reused
so tests should clean up after

tests: add cleanup after each test

---

.ostree/README.md
.ostree/get_ostree_data.sh
.ostree/packages-runtime.txt
.ostree/roles-runtime.txt
.sanity-ansible-ignore-2.10.txt
.sanity-ansible-ignore-2.11.txt
.sanity-ansible-ignore-2.12.txt
.sanity-ansible-ignore-2.13.txt
.sanity-ansible-ignore-2.14.txt
.sanity-ansible-ignore-2.15.txt
.sanity-ansible-ignore-2.9.txt
README-ostree.md
README.md
meta/collection-requirements.yml
tasks/main.yml
tasks/set_vars.yml
tests/tasks/cleanup.yml
tests/tasks/setup_test.yml
vars/main.yml

Feature: Allow running and testing the role with ostree managed nodes.
Reason: We have users who want to use the role to manage ostree
systems.
Result: Users can use the role to manage ostree managed nodes.

feat: support for ostree systems

---

.ansible-lint
.github/workflows/ansible-lint.yml
.github/workflows/ansible-managed-var-comment.yml
.github/workflows/ansible-plugin-scan.yml
.github/workflows/ansible-test.yml
.github/workflows/python-unit-test.yml

This is fixed by tox-lsr 3.2.2 - all actions that use tox-lsr are updated to
3.2.2, not just the python unit tests, even though the fix is only related to
pytest.  All roles are updated to use tox-lsr 3.2.2 for the sake of consistency
even if not affected by the pytest issue.
Something changed recently in the way github actions provisions systems which
means some of the directories are not readable by the python unit test actions.
In addition, the python unit tests were causing a lot of unnecessary directory
traversal doing collection/discovery of unit test files, because of using
`pytest -c /path/to/tox-lsr/pytest.ini` Unfortunately, with `pytest`, the
directory of the config file is the root directory for the tests and tests
discovery, and there is no way around this.
Therefore, the …

ci: fix python unit test - copy pytest config to tests/unit

---

tests/tasks/cleanup.yml

Tests that use the firewall must stop the firewall after the
test is complete to ensure the firewall will not cause problems
with subsequent tests of other roles.

test: stop firewall after tests that use firewall

---

filter_plugins/vpn_ipaddr.yml

Docs for filters must be in a separate file named the same as the
filter filename but with a .yml extension.

docs: vpn_ipaddr filter requires vpn_ipaddr.yml for docs

---

.github/workflows/ansible-lint.yml
.github/workflows/ansible-managed-var-comment.yml
.github/workflows/ansible-test.yml
.github/workflows/python-unit-test.yml
.github/workflows/qemu-kvm-integration-tests.yml

Use tox-lsr 3.12.0 for the new osbuild_config.yml feature for bootc and users
https://github.com/linux-system-roles/tox-lsr/pull/211

ci: use tox-lsr 3.12.0 for osbuild_config.yml feature
